<?php

namespace Echecs\pageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagesRepository extends EntityRepository
{
    
    public function findPagesOrdered()
    {
    return $this->getEntityManager()->createQuery('Select a from EchecspageBundle:Pages a Order by a.ordre')->getResult();		
    }
	
}
